export const GET_CITY_LIST_INITIAL = 'GET_CITY_LIST_INITIAL'
export const GET_CITY_LIST_START = 'GET_CITY_LIST_START'
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS'
export const GET_CITY_LIST_FAILED = 'GET_CITY_LIST_FAILED'

export const GET_WIDGET_LIST_INITIAL = 'GET_WIDGET_LIST_INITIAL'
export const GET_WIDGET_LIST_START = 'GET_WIDGET_LIST_START'
export const GET_WIDGET_LIST_SUCCESS = 'GET_WIDGET_LIST_SUCCESS'
export const GET_WIDGET_LIST_FAILED = 'GET_WIDGET_LIST_FAILED'

export const NOTIFICATION_CITY_WEATHER = 'NOTIFICATION_CITY_WEATHER'

export const ADD_WIDGET_INITIAL = 'ADD_WIDGET_INITIAL'
export const ADD_WIDGET_START = 'ADD_WIDGET_START'
export const ADD_WIDGET_SUCCESS = 'ADD_WIDGET_SUCCESS'
export const ADD_WIDGET_FAILED = 'ADD_WIDGET_FAILED'
