export const GET_RESPONSE_INITIAL = 'GET_RESPONSE_INITIAL'
export const GET_RESPONSE_START = 'GET_RESPONSE_START'
export const GET_RESPONSE_SUCCESS = 'GET_RESPONSE_SUCCESS'
export const GET_RESPONSE_FAILED = 'GET_RESPONSE_FAILED'
